#!/usr/bin/env python

###########################################################
#               --SCALABLE CLIENT--                      ##
#                                                        ##
###########################################################

import sys, getopt
import os, threading
import re, time
import smtplib
from datetime import date, timedelta

serverIP = "30.30.30.1"
serverPORT = "3490"
interfaceNumber = 0

#Fire linux command
def fire(cmd):
    os.system(cmd)

def deconfigureIP(ipStart):
    global interfaceNumber
    IP = "30.30.30."
    IP = IP + str(ipStart)
    cmd = "ifconfig eth0:" + str(interfaceNumber) + " " + IP + " netmask 255.255.0.0 down"
    print(cmd)
    fire (cmd)
    interfaceNumber = interfaceNumber + 1

def configureIP(ipStart):
    global interfaceNumber
    IP = "30.30.30."
    IP = IP + str(ipStart)
    cmd = "ifconfig eth0:" + str(interfaceNumber) + " " + IP + " netmask 255.255.0.0 up"
    print(cmd)
    fire (cmd)
    interfaceNumber = interfaceNumber + 1
    return IP

def startClient(clientIP):
    global serverIP
    cmd = "nohup .././client " + serverIP + " " + serverPORT + " G1,G2 " + str(clientIP) + " &"
    print(cmd)
    fire(cmd)

def main(argv):
    turnDownInterfaces = False

    try:
        opts, args = getopt.getopt(argv,"h:i:",["down","num=","help"])
    except getopt.GetoptError:
        print "\nInvalid Command. Refer utility help."
        sys.exit(2)

    for opt, arg in opts:
        if opt in ("--help"):
            print("./client --num <num_of_clients> -i <starting_octet_of_ip> [--down]")
            sys.exit()
        elif opt in ("--num"):
            numberOfClients = int(arg)
        elif opt in ("-i"):
            ipStart = int(arg)
        elif opt in ("--down"):
            turnDownInterfaces = True

    for count in range(numberOfClients):
        if turnDownInterfaces:
            deconfigureIP(ipStart + count)
        else:
            IP = configureIP(ipStart + count)
            startClient(IP)

if __name__ == "__main__":
   if len(sys.argv) > 1:
       main(sys.argv[1:])
   else:
       print "\nInvalid Command. Refer utility help."


